name: ipyflex_docs
channels:
  - conda-forge
dependencies:
  - python=3.*
  - nodejs
  - jupyter_sphinx
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbsphinx-link
  - jlpm
  - numpy
  - ipygany
  - ipywidgets
  - plotly
  - ipydatagrid
  - yfinance
  - myst-parser
